@startuml Communications diagram
skinparam linestyle ortho
left to right direction

label " " as external
rectangle "Thing" as thing

external -[plain]-> thing: setBazFromString
thing -[plain]-> thing: setBaz

@enduml
