@startuml Communications diagram
skinparam linestyle ortho
left to right direction

label " " as external
rectangle "Thing" as thing
rectangle "Dependency" as dependency

external -[dashed]-> thing: getDependencyBar
thing -[dashed]-> dependency: getBar


@enduml
