@startuml communication
skinparam linestyle ortho
left to right direction

label " " as external
component "Unit under test" {
  rectangle "Thing" as thing
}

external -[plain]-> thing: setFoo

@enduml
