@startuml communication
skinparam linestyle ortho
left to right direction

component "Unit under test" {
  rectangle "Thing" as thing
}
rectangle "Dependency" as dependency

thing -[dashed]-> dependency: getBar


@enduml
